apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "openmct-ingress"
  labels:
    app: openmct-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: "openmct"
            port:
              number: 8080
