apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  #namespace: ebpf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: iogbole/node-receiver:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: receiver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

